name: Update Download Counts
on:
#  schedule:
#    - cron: "0 */2 * * *"
  workflow_dispatch:
  repository_dispatch:
    types: [download]

jobs:
  update:
    name: Update Download Count
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Create Node Environment
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Should Run
        shell: bash
        id: should-run
        run: echo "::set-output name=out::$(node -e 'console.log(require(`./data/options.json`).useActions)')"
      - name: Install npm dependencies
        if: github.event_name == 'workflow_dispatch' || steps.should-run.outputs.out == 'true'
        uses: bahmutov/npm-install@v1.6.0
        with:
          working-directory: .github/workflows/dlCountApp
      - name: Run Download Count Script
        if: github.event_name == 'workflow_dispatch' || steps.should-run.outputs.out == 'true'
        run: node ./index.js
        working-directory: .github/workflows/dlCountApp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy
        if: github.event_name == 'workflow_dispatch' || steps.should-run.outputs.out == 'true'
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: download-api
          FOLDER: out
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
